name: ans21zs
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - torchvision=0.10.0
  - pytorch=1.9.0
  - cudatoolkit=11.1
  - ipykernel=5.3.4
  - jupyterlab=3.1.7
  - matplotlib=3.4.2
  - scikit-image=0.18.1
  - numpy=1.20.3
  - scikit-learn=0.24.2
  - tqdm=4.62.1
  - pandas=1.3.2
  - pip=21.0.1
  - pip:
    - opencv-contrib-python==4.5.3.56
